### PR TITLE
Fix incorrect topic Id generated due to race condition

### LINKED ISSUE #28: Incorrect topic Id due to race condition
When we enable tiered storage at a topic level which was created with a disabled mode, ConfigHandler attempts to invoke onLeadershipChange and here the topic ids are not present (yet).

```
replicaManager.remoteLogManager.foreach(rlm =>
        rlm.onLeadershipChange(leaderPartitions.toSet, followerPartitions.toSet, topicIds))
```

As a result, topicid defaults to something like the following:
```
[testng] [2022-03-14 23:26:16,885] WARN Previous cached topic id 4tN_eJuTTrSE3KMT8m2aKA for PhilCollins-0 does not match update topic id AAAAAAAAAAAAAAAAAAAAAA (kafka.log.remote.RemoteLogManager)
AAAAAAAAAAAAAAAAAAAAAA-0-0 --> 4tN_eJuTTrSE3KMT8m2aKA-0-0
```

This problem happens because the ConfigHandler relies on Log.scala -> Partition metadata file to be initialized with topic ids via LeaderAndISRRequest but in reality this is not the case. The Partition metadata file which stores the topic ids in all brokers are empty when this lookup is made.

The topicids are populated by the controller via LeaderAndISRRequest and this arrives after the ConfigHandler call to rlm.onLeadershipChange:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-516%3A+Topic+Identifiers#KIP516:TopicIdentifiers-PartitionMetadatafile

### PR DESCRIPTION
**Pull request by divijvaidya**
Resolves https://github.com/satishd/kafka/issues/28

## Problem
When we enable tiered storage at a topic level which was created with a disabled mode, ConfigHandler attempts to invoke onLeadershipChange and here the topic ids are not present (yet).

```
replicaManager.remoteLogManager.foreach(rlm =>
        rlm.onLeadershipChange(leaderPartitions.toSet, followerPartitions.toSet, topicIds))
```

As a result, topicid defaults to something like the following:
```
[testng] [2022-03-14 23:26:16,885] WARN Previous cached topic id 4tN_eJuTTrSE3KMT8m2aKA for PhilCollins-0 does not match update topic id AAAAAAAAAAAAAAAAAAAAAA (kafka.log.remote.RemoteLogManager)
AAAAAAAAAAAAAAAAAAAAAA-0-0 --> 4tN_eJuTTrSE3KMT8m2aKA-0-0
```

This problem happens because the ConfigHandler relies on Log.scala -> Partition metadata file to be initialized with topic ids via LeaderAndISRRequest but in reality this is not the case. The Partition metadata file which stores the topic ids in all brokers are empty when this lookup is made.

The topicids are populated by the controller via LeaderAndISRRequest and this arrives after the ConfigHandler call to rlm.onLeadershipChange:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-516%3A+Topic+Identifiers#KIP516:TopicIdentifiers-PartitionMetadatafile

## Changes
1. Remove ConfigHandler's dependency on Log.PartitionMetadata to fetch the instead fetch it from Zk.
2. Synchronise RemoteLogManager.onLeadershipChange

## Testing
Added unit tests

### CODE REVIEW

**Comment by divijvaidya** [comment]
@satishd @wyuka please take a look when you get a chance

File: core/src/main/scala/kafka/log/remote/RemoteLogManager.scala [hunk 1]
```diff
@@ -237,25 +238,39 @@ class RemoteLogManager(fetchLog: TopicPartition => Option[Log],
...
-        case (topicIdPartition, partition) =>
-          doHandleLeaderOrFollowerPartitions(topicIdPartition, _.convertToLeader(partition.getLeaderEpoch))
+    /**
+     * The following scenarios are possible when the onLeadershipChange method is invoked:
+     *
+     * 1. LeaderAndIsrRequest arrives before ConfigHandler config change for remoteStorageEnable: In this case, there will be a separate call for config change.
+     * 2. LeaderAndIsrRequest arrives after ConfigHandler config for remoteStorageEnable: In this case, the config changes will not be lost as there is a fetchLog call now to fetch the log updates.
+     * 3. LeaderAndIsrRequest arrives at same time as ConfigHandler config for remoteStorageEnable: Falls in to 1 or 2 above depending on sequencing
+     * 
+     * This method is safe for all the three scenarios and will be able to pick up the updated configuration.
```
Comment (wyuka) [inline core/src/main/scala/kafka/log/remote/RemoteLogManager.scala:264]: This is my understanding of the issue.

Either LeaderAndIsrRequest comes in first, or the Config change comes in first. If LeaderAndIsrRequest comes in first, we are happy because the first call will add the topicId to the map, and then RLM will be definitely initialized on the second call.

If ConfigHandler gets called first before LeaderAndIsr is received, and the broker doesn't yet have a topicId, then we can simply ignore the call in `maybeBootstrapRemoteLogComponents`. We will just update the log config to say RLM is enabled. Now, when the LeaderAndIsr request comes in, the config changes will not be lost and we will initialize RLM for the topic.

I have added this little check in our LinkedIn branch for this corner case.
https://github.com/linkedin/kafka/blob/3.0-li-rc1/core/src/main/scala/kafka/server/ConfigHandler.scala#L83-L87

Can you please explain if that check won't suffice for some corner case?

**Comment by kamalcph** [comment]
Thanks, @divijvaidya for this patch! We also have fixed this in our internal branch. I'll open a PR shortly. 

Tiered storage can only be enabled on topics with IBP as 2.8-IV1 which means all the topics should already have topic-id. There's a bug ([KAFKA-12426](https://issues.apache.org/jira/browse/KAFKA-12426)) in v2.8 which prevented topic-id from being saved to the partition.metadata file. 

When the remote log storage is enabled on a topic dynamically, the controller won't send LISR. The individual broker listens for the ZK config change notification and bootstrap/invokes the remote log components for the enabled partitions.

**Comment by kamalcph** [comment]
https://github.com/satishd/kafka/commit/6f48319e8b72a014890ca5644c7ecaf0e7e7effd

**Comment by satishd** [comment]
@divijvaidya Please resolve the conflicts.

**Comment by divijvaidya** [comment]
@satishd @kamalcph this should be ready for review again.

File: core/src/main/scala/kafka/log/remote/RemoteLogManager.scala (hunk 1 above)
Comment (divijvaidya) [reply core/src/main/scala/kafka/log/remote/RemoteLogManager.scala:264]: Hi Tirtha
I hope your question was answered by Kamal's comment below? The summary is that we won't get a LISR request in cases when TS is enabled dynamically and hence can't rely on them to update the topicID, hence, we changed the dependency to zookeeper directly.

File: core/src/main/scala/kafka/server/ConfigHandler.scala [hunk 2]
```diff
@@ -71,18 +71,32 @@ class TopicConfigHandler(private val replicaManager: ReplicaManager,
...
-  private[server] def maybeBootstrapRemoteLogComponents(topicIds: Map[String, Uuid],
+  private[server] def maybeBootstrapRemoteLogComponents(topic: String,
                                                         logs: Seq[Log],
                                                         wasRemoteLogEnabledBeforeUpdate: Boolean): Unit = {
+
+    def maybeFetchTopicId(topic: String, logs: Seq[Log]): Map[String, Uuid] = {
+      val topicId = Map(topic -> logs.head.topicId)
+        .filter(entry => entry._2 != Uuid.ZERO_UUID)
+        .getOrElse(topic,
+          replicaManager.zkClient.map(_.getTopicIdsForTopics(Predef.Set(topic))
```
Comment (satishd) [inline core/src/main/scala/kafka/server/ConfigHandler.scala]: This check can be simplified like below as it is easy to read.

```
 replicaManager.zkClient.getOrElse(throw new ConfigException(LogConfig.RemoteLogStorageEnableProp,
            logs.head.remoteLogEnabled(), s"Error occurred while setting the configuration as ZkClient is missing"))
            .getTopicIdsForTopics(Predef.Set(topic))
            .filter(entry => entry._2 != Uuid.ZERO_UUID)
            .getOrElse(topic, throw new ConfigException(LogConfig.RemoteLogStorageEnableProp,
              logs.head.remoteLogEnabled(), s"Error occurred while setting the configuration due to unavailability of topic ids for $topic")
```

**Review by satishd — COMMENTED** [review]
Thanks @karjag5 @divijvaidya for the PR. Overall LGTM, left a minor comment.

File: core/src/main/scala/kafka/server/ConfigHandler.scala (hunk 2 above)
Comment (divijvaidya) [reply core/src/main/scala/kafka/server/ConfigHandler.scala]: Thank you for the suggestion. I have changed it as per your suggestion in the latest commit.

**Comment by satishd** [comment]
Thanks @divijvaidya for addressing the review comments. LGTM.
